# This is a basic workflow to help you get started with Actions

name: Stage the app

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'stage')

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
